# 插件加载提示
welcome: 当你看到这句话的时候说明配置文件已经正常加载
# 此处填写你从Jx3api.com处获得的Token
jx3api_token: token
# 此处填写ticket
jx3api_ticket: ticket
# 机器人名称，会影响图片服务中的水印
bot_name: 剑3咕咕
# 团队招募屏蔽词(默认自带的是双二刷屏刷的贼凶的)
team_masked_words: [将夜,楼外,哈哈,大财,冻结,枕书,尘逸]
# 可以用于限制机器人功能的管理ID(实际使用中请将本人的ID替换上去，不删这个被我发现还去盈利小心被我鲨雕！)
admin: ['1787060816']

# 订阅数据的频道（仅限单文字频道，每个大服务器中可以独立订阅很多个频道推送）
# 新闻咨询订阅
news: []
# 版本更新订阅
version_fix: []
# 服务器状态订阅（开服监控）
server_status: []
# 吃瓜第一线！！（贴吧推送）
forum_post: []

blind_server:
  - 长安城: []
  - 龙争虎斗: []
  - 蝶恋花: []
  - 剑胆琴心: []
  - 幽月轮: []
  - 乾坤一掷: []
  - 斗转星移: []
  - 唯我独尊: []
  - 梦江南: []
  - 横刀断浪: []
  - 绝代天骄: []
  - 破阵子: []
  - 天鹅坪: []
  - 飞龙在天: []
  - 青梅煮酒: []